name: judouapp
description: 句读App 的 Flutter 版本

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http: ^0.12.0+1
  build_runner: ^0.9.0  #用于生成代码
  json_serializable: ^0.5.4 #序列化
#  image_downloader: ^0.12.0 #保存图片到本地
  cupertino_icons: ^0.1.2
  flutter_refresh : ^0.0.1 #上拉加载下拉刷新
  dio: ^1.0.0 #网络请求
  json_annotation: ^0.2.3
#  flutter_swiper : ^1.1.4
#  carousel_slider: ^1.1.0
  common_utils: 1.0.9 #工具类,https://pub.dartlang.org/packages/common_utils
  cached_network_image: ^0.6.2 #加载网络图片
  zoomable_image: ^1.3.1 #图片查看器
  fluttertoast: ^3.0.1 #弹窗
  jpush_flutter: ^0.0.11 #极光推送

  save_image_2_native: ^0.0.3 #保存图片到本地相册

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #tab图片
    - images/tab/tab_discover.png
    - images/tab/tab_discover_selected.png
    - images/tab/tab_home.png
    - images/tab/tab_home_selected.png
    - images/tab/tab_mine.png
    - images/tab/tab_mine_selected.png
    - images/tab/tab_moments.png
    - images/tab/tab_moments_selected.png
  #首页
    - images/home/home_title.png
    - images/home/icon_home_comment.png
    - images/home/icon_home_like.png
    - images/home/icon_home_like_selected.png
    - images/home/icon_home_share.png
    - images/home/icon_like.png
    - images/home/icon_like_selected.png
    - images/home/icon_author_reference_verified.png
  #动态
    - images/moments/icon_create_diary.png
    - images/moments/icon_create_sentence.png
    - images/moments/icon_create_status.png
    - images/moments/square/cell_more.png
    - images/moments/square/icon_collect.png
    - images/moments/square/icon_comment.png
    - images/moments/square/icon_like.png
    - images/moments/square/icon_share.png
    - images/moments/big_image_placeholder.png #占位图

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: NotoSansCJKsc-Light
      fonts:
        - asset: fonts/NotoSansCJKsc-Light.otf
